version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./screenshots_folder:/screenshots_folder
    environment:
      - PYTHONUNBUFFERED=1
      - SCREENSHOT_FOLDER=screenshots_folder
      - IS_EXPOSE_METRICS=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo
      - prometheus
    env_file:
      - .env
  screenshotter:
    image: python:latest
    command: ["python", "-m", "http.server", "5500"]
    ports:
      - "5500:5500"
    volumes:
      - ./docker_services/tiny_frontend:/app
    working_dir: /app

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker_services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "4001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis port
    networks:
      - mynetwork

volumes:
  mongo_data:
  grafana_data:

